[JENKINS-26677] Avoid using ServletException from SlaveComputer since it can break calls to SlaveComputer.getChannelToMaster. (#3778)
java.lang.NoClassDefFoundError: javax/servlet/ServletException
	at hudson.util.ProcessTree.get(ProcessTree.java:399)