Trying to make AsynchPeopleTest more robust. https://jenkins.ci.cloudbees.com/job/core/job/jenkins_main_trunk/1369/testReport/junit/hudson.model/AsynchPeopleTest/display/ org.junit.ComparisonFailure: expected:<[display: none;]> but was:<[]> 	at org.junit.Assert.assertEquals(Assert.java:115) 	at org.junit.Assert.assertEquals(Assert.java:144) 	at hudson.model.AsynchPeopleTest.display(AsynchPeopleTest.java:44) was presumably a race condition. Could reproduce by adding a Thread.sleep into AsynchPeople.compute. This patch (with waitForBackgroundJavaScript) avoids that error; but causes the assertNotNull at the end to fail, for reasons TBD.