[JENKINS-62006] Move getChannelToMaster to a separate class
This should avoid classloading issues I've seen, such as

Caused by: java.lang.NoClassDefFoundError:
javax/servlet/ServletException
  at hudson.util.ProcessTree.get(ProcessTree.java:432)
...