Avoid JavaScript errors on Plugin Manager pages
Because this code is being re-used across the different tabs under the Plugin
Manager pages, a number of calls were being made to Element.observe() with
`undefined` for the elements, throwing a :

    TypeError: registry is undefined ((prototype.js:5615:9)