Remove use of '<' and '>' which cause javadoc errors
Tested with Java 8 and "mvn javadoc:test-javadoc".  Eliminates errors such as:

    [ERROR] java/hudson/os/DCOMSandbox.java:18: error: bad use of '>'