Re-add hudson.UDPBroadcastFragment
The class was removed with f10d9f95fc ("[JENKINS-60913] Remove network
discovery services (#4460)") but is required by the swarm client. As
result, swarm clients are unable use Jenkins:

java.lang.NoClassDefFoundError: hudson/UDPBroadcastFragment
        at hudson.plugins.swarm.PluginImpl.getSwarmSecret(PluginImpl.java:262)

This commit re-adds hudson.UDPBroadcastFragment to jenkin's core, to
allow swarm client to the use the master again and hence fixes
JENKINS-61029.