not sure why this is failing a test but hopefully this would do?
Error is:

------
Legacy code started this job.  No cause information is available
Staging pom.xml
Parsing POMs
Discovered a new module test:test Unnamed - test:test:jar:0.1-SNAPSHOT
[workspace] $ /home/hudson/tools/linux-i586/java1.6.0_13/jre/bin/java -cp /home/hudson/workspace/hudson/hudson/main/maven-agent/target/maven-agent-1.318-SNAPSHOT.jar:/tmp/hudson734403729557882019test/maven-2.0.7/boot/classworlds-1.1.jar hudson.maven.agent.Main /tmp/hudson734403729557882019test/maven-2.0.7 /home/hudson/workspace/hudson/hudson/main/remoting/target/remoting-1.318-SNAPSHOT.jar /home/hudson/workspace/hudson/hudson/main/maven-interceptor/target/maven-interceptor-1.318-SNAPSHOT.jar 59419
&#0;&#0;&#0;channel started
Executing Maven:  -B -f /tmp/hudson5515991059914480682test/jobs/test0/workspace/pom.xml install
[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[INFO] Building Unnamed - test:test:jar:0.1-SNAPSHOT
[INFO]    task-segment: [install]
[INFO] ----------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The plugin 'org.jvnet.maven-antrun-extended-plugin:maven-antrun-extended-plugin' does not exist or no valid version could be found
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Fri Jul 31 10:02:09 PDT 2009
[INFO] Final Memory: 4M/8M
[INFO] ------------------------------------------------------------------------
channel stopped
Finished: FAILURE
------
 expected:<SUCCESS> but was:<FAILURE>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at org.jvnet.hudson.test.HudsonTestCase.assertBuildStatus(HudsonTestCase.java:519)
	at hudson.maven.RedeployPublisherTest.testBug2593(RedeployPublisherTest.java:48)


git-svn-id: https://hudson.dev.java.net/svn/hudson/trunk/hudson/main@20340 71c3de6d-444a-0410-be80-ed276b4c234a