Fix windows-slaves-plugin
2669e4a86d72f2d8b67417812db8f52aa487f3de extracted windows-slaves code
to a separate plugin.
However in the process, it introduced a dependency conflict.
core -> j-interop -> jcifs (1.2.19)
whereas
windows-slaves-plugin -> ... -> jcifs (1.3.17-kohsuke-1)

This was causing NoSuchMethodError while launching windows slaves