Remove dependency on ssh-slaves as its transitive dependency on credentials 2.1.2 breaks some tests with a NoSuchMethodError https://gist.github.com/cyrille-leclerc/cbe19b65b99753d92ea8c20cba0fbf5d