Gracefully detect the double loading of JNA instead of failing later with NoClassDefFoundError.
git-svn-id: https://hudson.dev.java.net/svn/hudson/trunk/hudson/main@23864 71c3de6d-444a-0410-be80-ed276b4c234a