[FIXED JENKINS-11960] NoSuchMethodError on slf4j on JBoss EAP 5.1 (cherry picked from commit 5bc37c2ad49d6093e9b912159faf0db0131273c5)
Conflicts:

	changelog.html
	maven-plugin/pom.xml