improved the error check more robust, based on the old xUnit plugin behavior:
unning from: /usr/share/jenkins/jenkins.war[Winstone 2011/03/28
16:52:46] - Beginning extraction from war file
hudson home directory: /var/lib/jenkins found at:
EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 28, 2011 4:52:47 PM hudson.util.CharacterEncodingFilter init
INFO: CharacterEncodingFilter initialized. DISABLE_FILTER: false
FORCE_ENCODING: false
[Winstone 2011/03/28 16:52:47] - HTTP Listener started: port=8081
Using one-time self-signed certificate
Mar 28, 2011 4:52:48 PM hudson.model.Hudson$5 onAttained
INFO: Started initialization
Mar 28, 2011 4:52:48 PM hudson.model.Hudson$5 onAttained
INFO: Listed all plugins
[Winstone 2011/03/28 16:52:49] - Winstone Servlet Engine v0.9.10
running: controlPort=disabled
Mar 28, 2011 4:52:57 PM hudson.plugins.greenballs.PluginImpl start
INFO: Green Balls!
Mar 28, 2011 4:52:57 PM hudson.model.Hudson$5 onAttained
INFO: Prepared all plugins
Mar 28, 2011 4:53:05 PM hudson.model.Hudson$5 onAttained
INFO: Started all plugins
Mar 28, 2011 4:53:05 PM hudson.model.Hudson$5 onAttained
INFO: Augmented all extensions
Mar 28, 2011 4:53:05 PM hudson.model.Hudson$5 onTaskFailed
SEVERE: Failed NullIdDescriptorMonitor.verifyId
java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.InitializerFinder.invoke(InitializerFinder.java:
114)
        at hudson.init.InitializerFinder
$TaskImpl.run(InitializerFinder.java:174)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at hudson.model.Hudson$4.runTask(Hudson.java:734)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)Caused by:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:
39)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:
25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at hudson.init.InitializerFinder.invoke(InitializerFinder.java:
110)
        ... 8 more
Caused by: java.lang.UnsupportedOperationException: The descriptor
registry with the called getId() method is not used. The descri
ptor redefines its own getInputMetric() method.
        at com.thalesgroup.hudson.plugins.xunit.types.CustomType
$CustomInputMetricDescriptor.getId(CustomType.java:66)
        at
hudson.diagnosis.NullIdDescriptorMonitor.verify(NullIdDescriptorMonitor.java:
65)
        at
hudson.diagnosis.NullIdDescriptorMonitor.verifyId(NullIdDescriptorMonitor.java:
76)
        ... 13 more
Mar 28, 2011 4:53:05 PM hudson.WebAppMain$2 run
SEVERE: Failed to initialize Hudson
org.jvnet.hudson.reactor.ReactorException: java.lang.Error:
java.lang.reflect.InvocationTargetException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:246)
        at hudson.model.Hudson.executeReactor(Hudson.java:752)
        at hudson.model.Hudson.<init>(Hudson.java:666)
        at hudson.model.Hudson.<init>(Hudson.java:606)
        at hudson.WebAppMain$2.run(WebAppMain.java:215)
Caused by: java.lang.Error:
java.lang.reflect.InvocationTargetException
        at hudson.init.InitializerFinder.invoke(InitializerFinder.java:
114)
        at hudson.init.InitializerFinder
$TaskImpl.run(InitializerFinder.java:174)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at hudson.model.Hudson$4.runTask(Hudson.java:734)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:
39)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:
25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at hudson.init.InitializerFinder.invoke(InitializerFinder.java:
110)
        ... 8 more
Caused by: java.lang.UnsupportedOperationException: The descriptor
registry with the called getId() method is not used. The descriptor
redefines its own getInputMetric() method.
        at com.thalesgroup.hudson.plugins.xunit.types.CustomType
$CustomInputMetricDescriptor.getId(CustomType.java:66)
        at
hudson.diagnosis.NullIdDescriptorMonitor.verify(NullIdDescriptorMonitor.java:
65)
        at
hudson.diagnosis.NullIdDescriptorMonitor.verifyId(NullIdDescriptorMonitor.java:
76)
        ... 13 more
Exception in thread "pool-2-thread-2" java.lang.NullPointerException
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Exception in thread "pool-2-thread-4" java.lang.NullPointerException
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor
$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

from http://jenkins.361315.n4.nabble.com/Jenkins-update-from-Hudson-on-Debian-broke-my-installation-td3413072.html