fix signup autofocus
the expression was not valid and caused an exception to be thrown.

replace the invalid expression with a null check (for the initial
rendering where there is no SignupIno in the page).

```
  10.912 [id=100]       WARNING h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: (data.errors.containsKey('username') || !data) ? true : null in /jenkins/securityRealm/createAccount. Reason: java.lang.Exception: expression not boolean valued
java.lang.Exception: expression not boolean valued
        at org.apache.commons.jexl.parser.ASTNotNode.value(ASTNotNode.java:68)
...
        at org.kohsuke.stapler.ScriptRequestDispatcher.forward(ScriptRequestDispatcher.java:97)
        at hudson.security.HudsonPrivateSecurityRealm.createAccount(HudsonPrivateSecurityRealm.java:399)
        at hudson.security.HudsonPrivateSecurityRealm._doCreateAccount(HudsonPrivateSecurityRealm.java:269)
        at hudson.security.HudsonPrivateSecurityRealm.doCreateAccount(HudsonPrivateSecurityRealm.java:261)
```