Remove use of '>' which cause javadoc errors
Tested with Java 8 and "mvn javadoc:test-javadoc".  Eliminates errors in other plugins such as multiple-scms-plugin,
such as:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:jar (attach-javadocs) on project multiple-scms: MavenReportException: Error while creating archive:
    [ERROR] Exit code: 1 - target/checkout/target/generated-sources/taglib-interface/org/jenkinsci/plugins/multiplescms/FormsTagLib.java:21: error: bad use of '>'
    [ERROR] *     The submission can be data-bound into List&lt;T> where T is the common base type for the describable instances.
    [ERROR]
    [ERROR] target/checkout/target/generated-sources/taglib-interface/org/jenkinsci/plugins/multiplescms/FormsTagLib.java:23: error: bad use of '>'