Looks like now HtmlUnit really depends on Xalan.
This was causing ui-samples test failure

java.lang.NoClassDefFoundError: org/apache/xml/utils/PrefixResolver
    at com.gargoylesoftware.htmlunit.html.DomNamespaceNode.getLocalName(DomNamespaceNode.java:81)
    at com.gargoylesoftware.htmlunit.html.HtmlElement.getNodeName(HtmlElement.java:308)
    at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.addNodeToRightParent(HTMLParser.java:636)
    at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.startElement(HTMLParser.java:610)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.cyberneko.html.HTMLTagBalancer.callStartElement(HTMLTagBalancer.java:1126)
    at org.cyberneko.html.HTMLTagBalancer.startElement(HTMLTagBalancer.java:734)
    at org.cyberneko.html.HTMLTagBalancer.forceStartElement(HTMLTagBalancer.java:758)
    at org.cyberneko.html.HTMLTagBalancer.startElement(HTMLTagBalancer.java:618)
    at org.cyberneko.html.HTMLTagBalancer.forceStartElement(HTMLTagBalancer.java:758)
    at org.cyberneko.html.HTMLTagBalancer.startElement(HTMLTagBalancer.java:586)
    at org.cyberneko.html.HTMLTagBalancer.forceStartElement(HTMLTagBalancer.java:758)
    at org.cyberneko.html.HTMLTagBalancer.forceStartBody(HTMLTagBalancer.java:828)
    at org.cyberneko.html.HTMLTagBalancer.endDocument(HTMLTagBalancer.java:468)
    at org.cyberneko.html.filters.DefaultFilter.endDocument(DefaultFilter.java:213)
    at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2064)
    at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:907)
    at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
    at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:901)
    at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:350)
    at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:304)
    at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:134)
    at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:101)
    at org.jvnet.hudson.test.HudsonPageCreator.createPage(HudsonPageCreator.java:46)
    at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:449)
    at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:332)
    at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:389)
    at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:374)
    at org.jvnet.hudson.test.HudsonTestCase$WebClient.getPage(HudsonTestCase.java:1717)
    at org.jvnet.hudson.test.HudsonTestCase.tearDown(HudsonTestCase.java:349)
    at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.tearDown(JellyTestSuiteBuilder.java:138)
    at org.jvnet.hudson.test.junit.GroupedTest.run(GroupedTest.java:50)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:97)
    at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:108)
    at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
    at $Proxy0.invoke(Unknown Source)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.utils.PrefixResolver
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 52 more
Caused by: java.lang.ClassNotFoundException: org.apache.xml.utils.PrefixResolver
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 52 more